name: Build
on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
      - "[0-9]+.[0-9]+.[0-9]+a[0-9]+"
      - "[0-9]+.[0-9]+.[0-9]+b[0-9]+"
permissions: read-all
concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true
jobs:
  setup_and_build:
    name: Setup and Build
    environment:
      name: uv
      url: https://github.com/${{github.repository}}/commits/${{github.ref_name}}
    env:
      UV_COMPILE_BYTECODE: "1"
      UV_LINK_MODE: "copy"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          token: ${{ secrets.GH_TOKEN }}
      - name: Install uv
        uses: astral-sh/setup-uv@b75a909f75acd358c2196fb9a5f1299a9a8868a4 # v6
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
          activate-environment: true
      - name: Install the project
        run: uv sync --no-dev --frozen --no-editable
      - name: Update Project Version
        run: uv version ${{ github.ref_name }}
      - name: Build source and wheel distribution
        run: uv build
      - name: Upload artifacts
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: dist
          path: dist/
      - name: Update the main branch to the updated version
        uses: stefanzweifel/git-auto-commit-action@778341af668090896ca464160c2def5d1d1a3eb0 # v6
        with:
          commit_message: "Version: ${{ github.ref_name }}"
          branch: main
          commit_options: --no-verify
      - name: Update the tag to the updated version
        run: |
          git tag --force ${{ github.ref_name }}
          git push origin --force HEAD:refs/tags/${{ github.ref_name }}
  github_release:
    name: Create GitHub Release
    needs: setup_and_build
    runs-on: ubuntu-latest
    environment:
      name: github
      url: https://github.com/${{github.repository}}/releases/tag/${{github.ref_name}}
    steps:
      - name: Checkout Code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - name: Download artifacts
        uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5
        with:
          name: dist
          path: dist/
      - name: Create GitHub Release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: >-
          gh release create ${{ github.ref_name }} dist/* --title ${{ github.ref_name }} --generate-notes
