name: Build
on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
      - "[0-9]+.[0-9]+.[0-9]+a[0-9]+"
      - "[0-9]+.[0-9]+.[0-9]+b[0-9]+"
permissions: read-all
concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true
jobs:
  setup_and_build:
    name: Setup and Build
    environment:
      name: uv
      url: ${{github.event.repository.html_url}}/commits/${{github.ref_name}}
    env:
      UV_COMPILE_BYTECODE: "1"
      UV_LINK_MODE: "copy"
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@95d9a5deda9de15063e7595e9719c11c38c90ae2 # v2.13.2
        with:
          egress-policy: audit

      - name: Checkout Code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          token: ${{ secrets.GH_TOKEN }}
      - name: Install uv
        uses: astral-sh/setup-uv@85856786d1ce8acfbcc2f13a5f3fbd6b938f9f41 # v7
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
          activate-environment: true
      - name: Install the project
        run: uv sync --no-dev --frozen --no-editable
      - name: Update Project Version
        run: uv version ${{ github.ref_name }}
      - name: Build source and wheel distribution
        run: uv build
      - name: Upload artifacts
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5
        with:
          name: dist
          path: dist/
      - name: Update the main branch to the updated version
        uses: step-security/git-auto-commit-action@e2d505468267a3cb406af729d48d664de1f16393 # v6.0.2
        with:
          commit_message: "Version: ${{ github.ref_name }}"
          branch: main
          commit_options: --no-verify
      - name: Update the tag to the updated version
        run: |
          git tag --force ${{ github.ref_name }}
          git push origin --force HEAD:refs/tags/${{ github.ref_name }}
  github_release:
    name: Create GitHub Release
    needs: setup_and_build
    runs-on: ubuntu-latest
    environment:
      name: github
      url: ${{github.event.repository.html_url}}/releases/tag/${{github.ref_name}}
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@95d9a5deda9de15063e7595e9719c11c38c90ae2 # v2.13.2
        with:
          egress-policy: audit

      - name: Checkout Code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - name: Download artifacts
        uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6
        with:
          name: dist
          path: dist/
      - name: Create GitHub Release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: >-
          gh release create ${{ github.ref_name }} dist/* --title ${{ github.ref_name }} --generate-notes
