name: Build
on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
      - "[0-9]+.[0-9]+.[0-9]+a[0-9]+"
      - "[0-9]+.[0-9]+.[0-9]+b[0-9]+"
permissions: read-all
concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true
jobs:
  setup_and_build:
    name: Setup and Build
    environment:
      name: uv
      url: ${{github.event.repository.html_url}}/commits/${{github.ref_name}}
    env:
      UV_LINK_MODE: "copy"
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@95d9a5deda9de15063e7595e9719c11c38c90ae2 # v2.13.2
        with:
          egress-policy: audit
      - name: Checkout Code
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
        with:
          token: ${{ secrets.GH_TOKEN }}
      - name: Install uv
        uses: astral-sh/setup-uv@1e862dfacbd1d6d858c55d9b792c756523627244 # v7
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
          activate-environment: true
      - name: Install the project
        run: uv sync --no-dev --frozen --no-editable
      - name: Update Project Version
        run: uv version ${{ github.ref_name }}
      - name: Build source and wheel distribution
        run: uv build
      - name: Build Python App with PyCrucible
        uses: razorblade23/pycrucible-action@6a5ce925bc1b078000d5540f44ebea266fa95cbd # v2
        with:
          output: dist/${{ github.event.repository.name }}-${{ github.ref_name }}
      - name: Upload artifacts
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5
        with:
          name: dist
          path: dist/
      - name: Update the main branch to the updated version
        uses: stefanzweifel/git-auto-commit-action@28e16e81777b558cc906c8750092100bbb34c5e3 # v7
        with:
          commit_message: "Version: ${{ github.ref_name }}"
          branch: main
          commit_options: --no-verify
      - name: Update the tag to the updated version
        run: |
          git tag --force ${{ github.ref_name }}
          git push origin --force HEAD:refs/tags/${{ github.ref_name }}
  github_release:
    name: Create GitHub Release
    needs: setup_and_build
    runs-on: ubuntu-latest
    environment:
      name: github
      url: ${{github.event.repository.html_url}}/releases/tag/${{github.ref_name}}
    permissions:
      contents: write
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@95d9a5deda9de15063e7595e9719c11c38c90ae2 # v2.13.2
        with:
          egress-policy: audit
      - name: Checkout Code
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
      - name: Download artifacts
        uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6
        with:
          name: dist
          path: dist/
      - name: Create GitHub Release
        uses: softprops/action-gh-release@5be0e66d93ac7ed76da52eca8bb058f665c3a5fe # v2.4.2
        with:
          files: dist/*
          draft: false
          prerelease: false
          make_latest: true
          fail_on_unmatched_files: true
          generate_release_notes: true
