name: Test
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true
permissions: read-all
jobs:
  compatibility:
    name: Check Dependency Compatibility
    runs-on: ubuntu-latest
    environment:
      name: code_quality
    permissions:
      checks: write
      contents: read
    env:
      UV_COMPILE_BYTECODE: "1"
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@95d9a5deda9de15063e7595e9719c11c38c90ae2 # v2.13.2
        with:
          egress-policy: audit
      - name: Checkout repository
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6
      - name: Check if the dependency files have changed
        id: changed-files-dependency
        uses: tj-actions/changed-files@24d32ffd492484c1d75e0c0b894501ddb9d30d62 # v47
        with:
          files: |
            pyproject.toml
            uv.lock
      - name: Install uv
        uses: astral-sh/setup-uv@5a7eac68fb9809dea845d802897dc5c723910fa3 # v7
        if: steps.changed-files-dependency.outputs.only_changed == 'true'
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
          activate-environment: true
      - name: Install the project
        if: steps.changed-files-dependency.outputs.only_changed == 'true'
        run: uv sync --frozen --no-install-project
      - name: Job Summary
        if: steps.changed-files-dependency.outputs.only_changed == 'true'
        run: |
          echo "## Dependency Tree" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo '<details>' >> $GITHUB_STEP_SUMMARY
          echo '<summary> Click me </summary>' >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          echo "$(uv tree --show-sizes)" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          echo '</details>' >> $GITHUB_STEP_SUMMARY
      - name: Job Summary - No Dependency Changes
        if: steps.changed-files-dependency.outputs.only_changed == 'false'
        run: |
          echo '## There is no change in dependency files ðŸ‘' >> $GITHUB_STEP_SUMMARY
  lint:
    name: Lint
    permissions:
      contents: write
      pull-requests: write
      checks: write
    needs: compatibility
    uses: ./.github/workflows/.lint.yaml
    secrets: inherit
  image:
    name: Test Image
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    needs: compatibility
    uses: ./.github/workflows/.docker.yaml
    with:
      is_test: true
      registry: ghcr.io
      install_source: git+${{ github.event.repository.html_url }}@${{ github.sha }}
    secrets: inherit
